definitions:
  github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse:
    properties:
      error:
        example: Bad Request
        type: string
    type: object
  github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.AcaoBrRequest:
    properties:
      cnpj:
        type: string
      codigo:
        type: string
      nome:
        type: string
      setor:
        type: string
    type: object
  github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.BdrRequest:
    properties:
      cnpj:
        type: string
      codigo:
        type: string
      nome:
        type: string
      setor:
        type: string
    type: object
  github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.FundoImobiliarioRequest:
    properties:
      cnpj:
        type: string
      codigo:
        type: string
      nome:
        type: string
      segmento:
        type: string
      tipo:
        type: string
    type: object
  github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.AcaoBrResponse:
    properties:
      cnpj:
        type: string
      codigo:
        type: string
      id:
        type: integer
      nome:
        type: string
      setor:
        type: string
    type: object
  github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.BdrResponse:
    properties:
      cnpj:
        type: string
      codigo:
        type: string
      id:
        type: integer
      nome:
        type: string
      setor:
        type: string
    type: object
  github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.FundoImobiliarioResponse:
    properties:
      cnpj:
        type: string
      codigo:
        type: string
      id:
        type: integer
      nome:
        type: string
      segmento:
        type: string
      tipo:
        type: string
    type: object
  pkg_api_v1.ErrorResponse:
    properties:
      error:
        example: Bad Request
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/acoes:
    get:
      consumes:
      - application/json
      description: Get All Ação BR
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.AcaoBrResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
      summary: Get All Acão BR
      tags:
      - acoes
    post:
      consumes:
      - application/json
      description: Create a new acao
      parameters:
      - description: AcaoBrRequest info
        in: body
        name: acao
        required: true
        schema:
          $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.AcaoBrRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.AcaoBrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
      summary: Create a acao
      tags:
      - acoes
  /api/v1/acoes/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a acao by ID
      parameters:
      - description: AcaoBr ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
      summary: Delete a acao
      tags:
      - acoes
    get:
      consumes:
      - application/json
      description: Get a Ação BR by ID
      parameters:
      - description: AcaoBr ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.AcaoBrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
      summary: Get a Acão BR
      tags:
      - acoes
    put:
      consumes:
      - application/json
      description: Update a acao by ID
      parameters:
      - description: AcaoBr ID
        in: path
        name: id
        required: true
        type: integer
      - description: AcaoBrRequest info
        in: body
        name: acao
        required: true
        schema:
          $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.AcaoBrRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.AcaoBrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1.ErrorResponse'
      summary: Update a acao
      tags:
      - acoes
  /api/v1/bdrs:
    get:
      consumes:
      - application/json
      description: Get All Ação BR
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.BdrResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Get All Acão BR
      tags:
      - bdrs
    post:
      consumes:
      - application/json
      description: Create a new bdr
      parameters:
      - description: BdrRequest info
        in: body
        name: bdr
        required: true
        schema:
          $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.BdrRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.BdrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Create a bdr
      tags:
      - bdrs
  /api/v1/bdrs/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a bdr by ID
      parameters:
      - description: Bdr ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Delete a bdr
      tags:
      - bdrs
    get:
      consumes:
      - application/json
      description: Get a Ação BR by ID
      parameters:
      - description: Bdr ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.BdrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Get a Acão BR
      tags:
      - bdrs
    put:
      consumes:
      - application/json
      description: Update a bdr by ID
      parameters:
      - description: Bdr ID
        in: path
        name: id
        required: true
        type: integer
      - description: BdrRequest info
        in: body
        name: bdr
        required: true
        schema:
          $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.BdrRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.BdrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Update a bdr
      tags:
      - bdrs
  /api/v1/fundos-imobiliarios:
    get:
      consumes:
      - application/json
      description: Get All Fundos Imobiliarios
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.FundoImobiliarioResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Get All Fundos Imobiliarios
      tags:
      - fundos-imobiliarios
    post:
      consumes:
      - application/json
      description: Create a new Fundo Imobiliario
      parameters:
      - description: FundoImobiliarioRequest info
        in: body
        name: fundoImobiliario
        required: true
        schema:
          $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.FundoImobiliarioRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.FundoImobiliarioResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Create a Fundo Imobiliario
      tags:
      - fundos-imobiliarios
  /api/v1/fundos-imobiliarios/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Fundo Imobiliario by ID
      parameters:
      - description: FundoImobiliario ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Delete a Fundo Imobiliario
      tags:
      - fundos-imobiliarios
    get:
      consumes:
      - application/json
      description: Get a Fundo Imobiliario by ID
      parameters:
      - description: FundoImobiliario ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.FundoImobiliarioResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Get a Fundo Imobiliario
      tags:
      - fundos-imobiliarios
    put:
      consumes:
      - application/json
      description: Update a Fundo Imobiliario by ID
      parameters:
      - description: FundoImobiliario ID
        in: path
        name: id
        required: true
        type: integer
      - description: FundoImobiliarioRequest info
        in: body
        name: fundoImobiliario
        required: true
        schema:
          $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_request.FundoImobiliarioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_MarcoADP_Investment-Manager_pkg_api_v1_response.FundoImobiliarioResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api_v1.ErrorResponse'
      summary: Update a Fundo Imobiliario
      tags:
      - fundos-imobiliarios
swagger: "2.0"
